### ISSUE TITLE
Would it be possible/sensible to make a new release for PyPi?

### ISSUE THREAD

**Issue by arrowtype** [LettError/ufoProcessor#56]
I’ve run into this issue again, and had to look it up:
https://github.com/LettError/ufoProcessor/issues/53

If I understand correctly, this is caused by a basic `pip install -U ufoProcessor` grabbing an older/outdated version of this library. The workaround is to install directly from the GitHub URL, but that seems somewhat error-prone, as this library is likely referenced in a number of pip requirements files.

Of course, it’s entirely possible I’m missing something, or that it’s a big hassle to update the package in PyPI, and I know you’re busy, Erik! But, if this update is feasible to make soonish, I think that could be helpful. If not, that’s also understandable, and this issue is just here for future reference.

Thank you, as always!

**Comment by LettError** [comment]
Would this be helped by making a release?

**Comment by punchcutter** [comment]
We need a new release so we can pass the `strict` flag from `makeinstancesufo` in afdko. Is there any reason not to make a new release?

**Comment by LettError** [comment]
This contains support for the `strict` flag. And a couple of other things. 
https://github.com/LettError/ufoProcessor/releases/tag/1.11

**Comment by alerque** [comment]
Will new releases be published on PyPi or should I switch e.g. Arch Linux packages to Git sources?

**Comment by LettError** [comment]
I have not published something on PyPi before.

**Comment by punchcutter** [comment]
Since it's been a while things are a little stale, but we (Adobe) have been doing the PyPI releases. Now that we are getting a new release we should remove the travis integration and add a GitHub action for publishing to PyPI. I can open a PR for that. The versioning is still not correct for the workflow since it should be expecting the format `'\d+\.\d+\.[0-9a-z]+'` and currently the version is missing another place. So we should probably do a 1.13.0 to get back in sync.

**Comment by LettError** [comment]
I will up the tag and version to 1.13.0 
A PR / assistance for PyPi would be much appreciated.

**Comment by punchcutter** [comment]
Ok, I opened a PR with a simple GitHub action to run the PyPI release. We could add a lot more actions for testing and making the actual release, but I don't know how needed any of that is right now so this should suffice for now. Since you already added the 1.13.0 tag this won't automatically run when merged. If you merge the PR you can then go to Actions and you'll see **Upload Python Package** on the left. 

![Screenshot 2024-08-15 at 1 18 27 PM](https://github.com/user-attachments/assets/6fcfeff7-2342-4af0-b599-62f83a2a41e5)

If you click that you should see a Run workflow pulldown on the right

![Screenshot 2024-08-15 at 1 18 35 PM](https://github.com/user-attachments/assets/39b6c646-4b81-4656-99a4-a8f21f0abf71)

If you click that you can choose to Run workflow and it will do the PyPI release. 

![Screenshot 2024-08-15 at 1 19 15 PM](https://github.com/user-attachments/assets/68d62b3b-3769-4e97-857d-eab2fc366547)

**Comment by punchcutter** [comment]
Ok, we went ahead and re-pushed the 1.13.0 tag to trigger the release and make sure it's working. Next time you push a new tag it will get uploaded to PyPI if the versioning format is like I mentioned above `'\d+\.\d+\.[0-9a-z]+'`
So you can do an alpha or beta release for testing like `1.13.0a` before doing a full release.

**Comment by punchcutter** [comment]
Since there's a new release now I think this can be closed.
